### ISSUE TITLE
Tracking Issue for `tuple_array_conversions`

### ISSUE THREAD

**Issue by dswij** [rust-lang/rust-clippy#11151]
### Description

`tuple_array_conversions` was moved to `nursery` because of false positives. This issue tracks the FPs that need to be fixed before it can be moved back to `complexity`.

- [ ] https://github.com/rust-lang/rust-clippy/issues/11082
- [ ] https://github.com/rust-lang/rust-clippy/issues/11085
- [ ] https://github.com/rust-lang/rust-clippy/issues/11100
- [ ] https://github.com/rust-lang/rust-clippy/issues/11124
- [ ] https://github.com/rust-lang/rust-clippy/issues/11144

**Comment by dswij** [comment]
> I think a discussion is warranted before increasing the lint level, personally I find the suggested replacement substantially less readable

Fair enough, I'll bring this up in Zulip

**Comment by jhpratt** [comment]
This should not trigger in `const` contexts until const traits are stable.
