### ISSUE TITLE
Tracking Issue: Prevent duplicate diagnostic emission of lints

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#12379]
### Description

Follow up to https://github.com/rust-lang/rust-clippy/pull/12374

That PR added the `-Zdeduplicate-diagnostics=yes` flag to the following test files, to suppress the warning that will now be produced should new lints/tests emit duplicated diagnostics. Old lints should still be cleaned up though. Those are the test files that were affected:

- [ ] `tests/ui/nonminimal_bool.rs`
- [ ] `tests/ui/std_instead_of_core.rs`
- [ ] `tests/ui/min_rust_version_invalid_attr.rs`
- [ ] `tests/ui/nonminimal_bool_methods.rs`
- [ ] `tests/ui/type_complexity.rs`
- [ ] `tests/ui/renamed_builtin_attr.rs`
- [ ] `tests/ui/ptr_as_ptr.rs`
- [ ] `tests/ui/option_option.rs`
- [ ] `tests/ui/identity_op.rs`
- [ ] `tests/ui/indexing_slicing_index.rs`
- [ ] `tests/ui/many_single_char_names.rs`
- [ ] `tests/ui/manual_retain.rs`
- [ ] `tests/ui/mut_mut.rs`
- [ ] `tests/ui/single_match_else.rs`
- [ ] `tests/ui/suspicious_operation_groupings.rs`
- [ ] `tests/ui/single_match.rs`
- [ ] `tests/ui/else_if_without_else.rs`
- [ ] `tests/ui/unknown_attribute.rs`
- [ ] `tests/ui/no_effect_replace.rs`
- [ ] `tests/ui/assign_ops2.rs`

To fix some of those:
1. Pick one test and leave a comment about it
2. Remove the `-Zdeduplicate-diagnostics=yes` flag from it
3. Figure out the cause of duplicated diagnostic
4. Fix it and write a comment here so that it gets marked as resolved.

**Comment by UlazkaMateusz** [comment]
Hey,  tests/ui/type_complexity.rs is fixed and merged

**Comment by flip1995** [comment]
Thanks, only 7 to go :rocket: I love how well this works, we have amazing contributors!

**Comment by grtn316** [comment]
It appears the duplicate diag messages for:tests/ui/indexing_slicing_index.rs may be coming from the compiler instead of this project.

**Comment by Gri-ffin** [comment]
Hi, both `tests/ui/unknown_attribute.rs` and `tests/ui/renamed_builtin_attr.rs` were fixed in #17164

**Comment by Gri-ffin** [comment]
Hi, the duplicate diagnostics of `suspicious_operation_groupings` was fixed.

**Comment by CBSpeir** [comment]
It looks `tests/ui/nonminimal_bool_methods.rs` can be marked resolved. Fixed by https://github.com/rust-lang/rust-clippy/pull/12845
