### ISSUE TITLE
Tracking Issue: Fix auto-applicable lint suggestions by using multipart suggestions

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#13099]
### Description

#13098 introduced `@no-rustfix` annotations, that can be removed by changing the suggestion to a multipart suggestion:
```rust
//@no-rustfix: need to change the suggestion to a multipart suggestion
```

The affected test files are:

- [x] `ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.rs`
- [x] `ui/crashes/ice-3717.rs`
- [x] `ui/derivable_impls.rs`
- [x] `ui/index_refutable_slice/if_let_slice_binding.rs`
- [x] `ui/index_refutable_slice/slice_indexing_in_macro.rs`
- [x] `ui/let_unit.rs`
- [x] `ui/manual_assert.rs`
- [x] `ui/manual_async_fn.rs`
- [x] `ui/manual_split_once.rs`
- [x] `ui/match_same_arms2.rs`
- [x] `ui/significant_drop_tightening.rs`
- [x] `ui/unnecessary_iter_cloned.rs`
- [x] `ui/unnecessary_to_owned.rs`

To fix some of those:

1. Pick one test and leave a comment about it
2. Remove the `@no-rustfix` annotation
3. Change the lint suggestion building to use `multipart_suggestion` over the current implementation
4. write a comment here or mention this issue in the PR so that it gets marked as resolved.

**Comment by ibilalkayy** [comment]
Hey @flip1995, I just sent a PR to solve a problem that you mentioned in this issue. Thank you!

**Comment by flip1995** [comment]
Copying a comment by `@kyoto7250`, that explains the tasks here a bit better than I have in the issue: https://github.com/rust-lang/rust-clippy/pull/13216#issuecomment-2286122609

> I [kyoto7250] have created a PR that fixes one of the files in this issue. #13230
> 
> In PR #13098, all tests that were expected to split into multipart files have been deleted and set to be skipped using `@no-rustfix`. Therefore, simply removing the annotation is not sufficient.
> 
> You remove `@no-rustfix` and run `cargo uitest` locally, the tests should fail. For more details, please refer to the following documentation:
> 
> https://github.com/rust-lang/rust-clippy/blob/master/book/src/development/writing_tests.md
> 
> In my PR, multiple files were not generated, but I believe that in this issue, it is expected that multiple files will be generated by the multipart suggestion.

**Comment by scottgerring** [comment]
#13717 has been reviewed ✅  but not merged .

I think ** ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.rs** is already good?: 

https://github.com/rust-lang/rust-clippy/blob/479e1fc7c0056fc269da78a75397b9c25c5635d5/clippy_lints/src/index_refutable_slice.rs#L158-L177

**Comment by scottgerring** [comment]
I pushed a change for `ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.rs` above too.

**Comment by scottgerring** [comment]
Hey @flip1995 , if you have a chance, do the PRs i've pushed look good to you? I'm happy to do more of these but it looks like the PR approval lag is high and I am hesitant to continue until i've got a positive signal!

**Comment by flip1995** [comment]
Sorry for not replying. I'm also pretty backed up right now. I just found some time for giving your PRs a look. They LGTM (and I already merged one 🎉 ).

**Comment by scottgerring** [comment]
No worries - thanks for finding the time! I'll knock a few more off in the coming days 💪

**Comment by scottgerring** [comment]
I've started on `ui/let_unit.rs` but it's a bit fiddlier - i'll push a PR for this early next week.

**Comment by scottgerring** [comment]
Hey @flip1995 , I reckon i've got my head around these. If you're happy for me to pick up the rest, feel free to assign the issue to me!
Would it be easier to continue doing PR-per-lint or should I bundle them up?

**Comment by flip1995** [comment]
You can do PR-per lint, that's easier to review. I'll try to get to reviewing them as fast as I can, but that is currently quite slow. Sorry about that 😐

**Comment by flip1995** [comment]
FYI: You can self-assign issues by writing a comment with

```
@rustbot claim
```

in it.

**Comment by nanvel** [comment]
Hi, a fix for `unnecessary_to_owned`: https://github.com/rust-lang/rust-clippy/pull/13847
looking for a review.

**Comment by scottgerring** [comment]
All of these are either done or have an open PR apart from ` ui/unnecessary_iter_cloned.rs` which I will knock out tomorrow. @flip1995 , do you mind updating the issue text at the top - I don't think I have that power ?!

**Comment by scottgerring** [comment]
* let_unit: #13754 
* manual_assert: #13787 
* manual_split_once: #13789
* unnecessary_iter_cloned:  #13848

**Comment by scottgerring** [comment]
All done pending the last two merges 💪

**Comment by y21** [comment]
Looks like the list is complete. Thanks to everyone who worked on this :)
