### ISSUE TITLE
Tracking issue for RFC 2476, Clippy 1.0

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#3343]
This is a tracking issue for the RFC "Clippy 1.0" (https://github.com/rust-lang/rfcs/pull/2476). 

**Steps:**

- [x] `shadow_unrelated` should be moved from `restriction` to `pedantic`
- [x] `explicit_iter_loop` and `explicit_into_iter_loop` be moved from `style` to `pedantic`
- [ ] Add a version flag to Clippy that says 1.0
- [ ] Update clippy_dummy published crate to 1.0

**Unresolved questions:**

None. The question of uplifts has been split out of this RFC into https://github.com/rust-lang/rust/issues/53224

There isn't a "stabilization" step here per se, though we may consider moving the `clippy-preview` rustup component to `clippy` cc @nrc

**Comment by Manishearth** [comment]
Looks like the lint levels were changed already, i vaguely recall this happening during the rfc.

Anyone want to add the version flag?

**Comment by Centril** [comment]
Should the repo itself be moved to the `rust-lang` organization now to make it more official?

**Comment by Manishearth** [comment]
I certainly wouldn't mind, but rustfmt is still on the nursery and we've
been pretty explicitly trailing behind rustfmt on such things.

cc @nrc

**Comment by nrc** [comment]
I'd be happy for the repo to move to rust-lang, but I don't see a great rush. I plan to move rustfmt at some point after the 1.0 release, probably as soon as I have time to do it.

**Comment by oli-obk** [comment]
during such a move we could also drop the `rust-` prefix on the repo name

**Comment by retep998** [comment]
The repo was moved to `rust-lang` but the `rust-` prefix was not dropped.
