### ISSUE TITLE
[Roadmap] Documents requested by the Rust roadmap

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#6627]
According to the [Rust Roadmap 2021], a document specifying what it means to be
a member of the team should be produced. This should not put more pressure on
the team members, but rather help them and interested folks to know what the
expectations are. With this it should also be easier to recruit new team members
and may encourage people to get in touch, if they're interested to join.

[Rust Roadmap 2021]: https://github.com/rust-lang/rfcs/pull/3037

Steps to completion:
- [ ] What does this group do? DARCI
    - Decision maker
    - Accountable
    - Responsible
    - Consulted
    - Informed
- [ ] How does this group make decisions?
- [ ] What is expected of members to be part of this group?
- [ ] Where does this group work?
- [ ] Who is the point of contact for questions on the state of this group?

---

- Scale up the team to make it more robust

**Comment by xFrednet** [comment]
The team descriptions are saved in the [rust-lang/governance](https://github.com/rust-lang/governance) repo. There are already some common descriptions that can be reused or linked to, for example for the [DARCI framework](https://github.com/rust-lang/governance/blob/master/common/darci.md), [vacation policy](https://github.com/rust-lang/governance/blob/master/common/vacation_policy.md) etc. :upside_down_face:

**Comment by flip1995** [comment]
We should wait until the core team contacts us. Until then we don't have to do anything here.

**Comment by xFrednet** [comment]
Sure, I was just looking through the roadmap for fun and linked what I found for future reference. I didn't want to start or imply anything with that :sweat_smile:. Thank you for the clarification :upside_down_face:
