### ISSUE TITLE
[Roadmap] Better issue and PR triage

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#6629]
To get a handle on the influx of open issues, a process for triaging issues and
PRs should be developed. Officially, Clippy follows the Rust triage process, but
currently no one enforces it. This can be improved by sharing triage teams
across projects or by implementing dashboards / tools which simplify triaging.

- [x] Get people dedicated to triage Clippy issues and PRs
- [x] Implement Dashboard for Issues and PRs to make triaging easier
- [ ] Share triage teams across repositories

**Comment by giraffate** [comment]
>  Implement Dashboard for Issues and PRs to make triaging easier

I partially work on this. I'm prototyping a dashboard for PRs, discussed at [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/can.20we.20automate.20triaging.20PRs.20a.20bit.3F).

**Comment by flip1995** [comment]
@giraffate I assigned you to this issue, since you already put so much work into it.

**Comment by flip1995** [comment]
Link to dashboard repo (WIP): https://github.com/giraffate/toriage

**Comment by giraffate** [comment]
I have some updates, see https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/can.20we.20automate.20triaging.20PRs.20a.20bit.3F/near/227444152.

**Comment by giraffate** [comment]
Discussion on Zulip t-infra is here: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Triage.20PR.20dashboard.

**Comment by giraffate** [comment]
Some updates
- The PR dashboard was merged into triagebot: <https://github.com/rust-lang/triagebot/pull/1223>
- But it doesn't work on production for some reasons: <https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Triage.20PR.20dashboard/near/229336937>

**Comment by giraffate** [comment]
The PR dashboard works now: <https://triage.rust-lang.org/triage/rust-lang/rust-clippy>. Thanks!

**Comment by flip1995** [comment]
I think we can close this issue, since we have the triage dashboard working for quite some time now. @giraffate thanks for all the triage work you're doing in addition to reviewing and for implementing the triage dashboard!
