### ISSUE TITLE
[Tracking Issue] Refactor lints in methods module

### ISSUE THREAD

**Issue by TaKO8Ki** [rust-lang/rust-clippy#6886]
This issue is linked with https://github.com/rust-lang/rust-clippy/issues/6680.

I've refactored most of lints in methods module in https://github.com/rust-lang/rust-clippy/pull/6826 and the PR became too large.
So, I'm going to refactor the rest of lints and move some functions to `clippy_lints/src/utils/methods/` in a new PR.

This issue is a tracking issue for doing this to avoid opening a too large PR and split them into small PRs.

TODO
- [x] refactor lints other than `CHARS_NEXT_CMP` and `CHARS_LAST_CMP` in https://github.com/rust-lang/rust-clippy/pull/6826
- [x] refactor `CHARS_NEXT_CMP`
- [x] refactor `CHARS_LAST_CMP`
- [x] https://github.com/rust-lang/rust-clippy/pull/6826#discussion_r592666575
- [x] move functions such as `derefs_to_slice` to `clippy_lints/src/utils/methods/`
review comments
- [x] https://github.com/rust-lang/rust-clippy/pull/6826#discussion_r592175734
- [x] https://github.com/rust-lang/rust-clippy/pull/6826#pullrequestreview-610134346
- [x] move checks that decide whether the lint is triggered to each module.
review comment: https://github.com/rust-lang/rust-clippy/pull/6826#discussion_r592186377
