### ISSUE TITLE
[Tracking issue] New lint metadata collection (a metadata collection monster)

### ISSUE THREAD

**Issue by xFrednet** [rust-lang/rust-clippy#7172]
This issue tracks the effort to replace the current lint documentation collection with a new Rust implementation. The implementation will be based on a lint to access rustc's type information (See #4310 for further information). The first incomplete version of *the metadata collection monster* (as I like to call it) got merged in #6887.

### To-Do list
* [x] Collect lint metadata
    * [x] The lint ID
    * [x] The lint declaration file and location (for #1303)
    * [x] The lint group
    * [x] The documentation
    * [x] The applicability (if resolvable)
    * [x] Is the suggesting a multi-part-suggestion? (if resolvable) 
* [x] Collect deprecated lints 
    * [draft](https://github.com/xFrednet/rust-clippy/tree/4310-depreciated-lints-collection)
    * PR #7197
    * backup implementation to collect from `store.register_removed` [commit](https://github.com/xFrednet/rust-clippy/commit/90edfd514624b979f99d3f133f968dd19d908d09)
* [x] Collect lint configuration values 
    * PR #7214
* [x] Create a simple way to run the lint collector, maybe via a cargo alias
    * PR #7217
* [x] Rerun the collection after touching the `clippy_lints/src/lib.rs` if nothing was collected due to caching (See comments in this issue)
  * PR #7256
* [x] Remove `clippy::` prefix from lint group and add the lint level 
  * PR #7246
* [x] Switch the CI over to use the new collection
  * Discussion about this in #7229
  * PR #7298
* [x] Adapt [Clippy's lint list](https://rust-lang.github.io/rust-clippy/master/index.html) to support the new metadata format (Example output file: [`metadata_collection.json`](https://gist.github.com/xFrednet/6b9e2c3f725f476ba88db9563f67e119))
  * PR #7279
* [x] Remove old implementation
* [x] Collect renamed lints (https://github.com/rust-lang/rust-clippy/pull/8843 Thanks to @Serial-ATA)
* [x] Update documentation
    * [x] Lint configuration doc comment schema
    * [x] Registering deprecated lints
    * [x] Update configuration section template to use `### Configuration` instead of `**Configuration**`
* [x] Collect implementation version (See #6492)

### Needs investigation / discussion
* [x] Look into speeding up the collection by only registering the collection lint itself. (Suggested by @flip1995 [here](https://github.com/rust-lang/rust-clippy/pull/6887#issuecomment-830179118)) (Related discussion about [registration](https://github.com/rust-lang/rust-clippy/pull/7197#discussion_r629282595))
  * Done by flip1995 in PR #7253
* [x] Maybe include the lint output for the examples if it's not too much effort. (Suggested [here](https://github.com/rust-lang/rust-clippy/pull/7279#issuecomment-867692601))

---

@rustbot label +C-tracking-issue

**Comment by flip1995** [comment]
Found a "bug" while syncing: If you re-run the `cargo collect-metadata` command, it won't re-produce the `json` file again, since it thinks that it already ran on the crate and no re-check is necessary.

**Comment by xFrednet** [comment]
Jup, this was also mentioned in #7217. Is there a simple way to force a re-check. I usually used `cargo clean` which seems a bit excessive though?

**Comment by flip1995** [comment]
There's a hacky way in `touch`ing `clippy_lints/src/lib.rs`. So `touch clippy_lints/src/lib.rs && cargo collect-metadata` will re-run the tool, but will also re-build clippy before re-running the tool. `cargo` has no `--force` flag though (AFAIK).

**Comment by xFrednet** [comment]
Using `touch` is still quicker than cleaning the entire project. We could maybe include a check in the `run_metadata_collection_lint()` test that touches the file and reruns the collection if the JSON output file was not updates or doesn't exist. It's hacky but a bit better than touching the file each time. What do you think?

**Comment by flip1995** [comment]
Yes, that was also my idea.

**Comment by xFrednet** [comment]
Okay, would you like to do this change as part of the CI, or shall I have a look into it? :upside_down_face:

**Comment by flip1995** [comment]
> Okay, would you like to do this change as part of the CI, or shall I have a look into it?

It doesn't matter for CI, since Clippy will be rebuild for this anyway. :D

**Comment by xFrednet** [comment]
I've adapted the website to use the new `lints.json` format in [`xfrednet:7172-adapt-website-to-new-format`](https://github.com/xFrednet/rust-clippy/tree/7172-adapt-website-to-new-format). A preview of the changes can be seen here: https://xfrednet.github.io/rust-clippy/master/index.html.

I'm not particularly good when it comes to designing GUIs. Any feedback is welcome :upside_down_face:.

**Comment by xFrednet** [comment]
Looking at the lint description, it looks like it's finally time to close this issue for good. @flip1995 Thank you for the mentoring on this one. This really introduced me to Clippy, and it's nice to see that the infrastructure still runs <3
