### ISSUE TITLE
[Tracking Issue] Refactor lints in misc_early module

### ISSUE THREAD

**Issue by TaKO8Ki** [rust-lang/rust-clippy#7208]
This issue is linked with #6680.

I've refactored some lints in misc_early module in https://github.com/rust-lang/rust-clippy/pull/7166.

This issue is a tracking issue for splitting the lints one by one, and move them into where they fit most instead of creating a new directory named misc_early.

- [ ] builtin_type_shadow
- [ ] double_neg
- [ ] mixed_case_hex_literals
- [ ] redundant_pattern
- [ ] unneeded_field_pattern
- [ ] unneeded_wildcard_pattern
- [ ] unseparated_literal_suffix
- [ ] zero_prefixed_literal
