### ISSUE TITLE
New lint: generalize `exit`, `todo`, `mem_forget`, etc.

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust-clippy#8031]
### What it does

The new lint(s) would be a generalization of other lints that check for usage of some functions, types, macros, etc.:

  - [x] [`exit`](https://rust-lang.github.io/rust-clippy/master/index.html#/exit) could be generalized to take a list of functions to check for (including those of the same project, not just the standard library).
    + Handled now by [`disallowed_methods`](https://rust-lang.github.io/rust-clippy/master/index.html#/disallowed_methods).
  - [x] [`todo`](https://rust-lang.github.io/rust-clippy/master/index.html#/todo) could be generalized to take a list of macros too.
    + Handled now by [`disallowed_macros`](https://rust-lang.github.io/rust-clippy/master/index.html#/disallowed_macros).
  - [ ] [`undocumented_unsafe_blocks`](https://rust-lang.github.io/rust-clippy/master/index.html#/undocumented_unsafe_blocks) could be generalized to other comments apart from `// SAFETY: ...` (for [`unsafe_code`](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unsafe-code)).
    +  `// PANIC: ...` for [`panic`](https://rust-lang.github.io/rust-clippy/master/index.html#/panic), [`unwrap_used`](https://rust-lang.github.io/rust-clippy/master/index.html#/unwrap_used)...
    + `// CAST: ...` for [`as_conversions`](https://rust-lang.github.io/rust-clippy/master/index.html#/as_conversions) (and related ones).
    + Partially related to [`lint_reasons`](https://github.com/rust-lang/rust/issues/54503)'s `reason = "..."`, Cc @xFrednet.
  - [ ] [`missing_safety_doc`](https://rust-lang.github.io/rust-clippy/master/index.html#/missing_safety_doc) could be generalized to `# Panics` sections (even if it only catches a subset of cases).
  - [`mem_forget`](https://rust-lang.github.io/rust-clippy/master/index.html#/mem_forget) gives another idea for generalization: for each function in the list, optionally give a list of traits to check to (not) be implemented for their arguments.
  - It could also be generalized to take paths only or do the matching textually (possibly including regex support).

etc. It would be a continuation of other lints such as [`disallowed_methods`](https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_methods) and [`disallowed_types`](https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_types).

The new lint(s) would be useful for big projects that may want to avoid particular items coming from dependencies, or to discourage their usage in general (requiring an explicit `allow`), or to deprecate certain items (while keeping existing ones), etc.

### Categories (optional)

- Kind: restriction.

### Drawbacks

None (since projects would be responsible for the lists).

**Comment by xFrednet** [comment]
We have the [`disallowed_methods`](https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_methods) and [`disallowed_types`](https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_types) lints. Having this for functions sounds reasonable. Macros can be a bit iffy but might be worth a try :upside_down_face:

**Comment by ojeda** [comment]
Thanks! I will add the links to the OP message.

**Comment by Veykril** [comment]
> We have the [disallowed_methods](https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_methods) and [disallowed_types](https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_types) lints. Having this for functions sounds reasonable. Macros can be a bit iffy but might be worth a try 🙃

If I see this right `disallowed_methods` already handles functions in general no? Macros seem to be handled since https://github.com/rust-lang/rust-clippy/pull/9495 as well now, what exactly would be left for this issue (I am unsure I understand the remaining points in the main issue text)?

**Comment by ojeda** [comment]
Indeed, some of this seems to be covered now. I have updated the list above -- we may want to split this into different issues.
